### ISSUE TITLE
Low  iptm+ptm value

### ISSUE THREAD

**Issue by cfz1998** [HommaF/AlphaFold2_chapter#1]
Hi! @HommaF 

I'm using `alphafold` to structure prediction for "PiP1+EpiC2B". But I get very low `iptm+ptm` value.
Running code:
```
bash /data/chaofan/software/alphafold-2.3.1/run_alphafold.sh -c reduced_dbs -d /data/chaofan/source/00.alphafold_database/ -o ./dummy_test/ -f t.fa -t 2023-10-17 -m multimer -l 1
```

Input_Fasta:
```
>Pip1
RNLKELSMLERHENWMVHHGRVYKDDIEKEHRFKTFKENVEFIESFNKNGTQRYKLAINKYADLTTEEFTTSFMGLDTSLLSQQESTATTTSFKYDSVTEVPNSMDWRKRGSVTGVKDQGVCGCCWAFSAAAAIEGAYQIANNELISLSEQQLLDCSTQNKGCEGGLMTVAYDFLLQNNGGGITTETNYPYEEAQNVCKTEQPAAVTINGYEVVPSDESSLLKAVVNQPISVGIAANDEFHMYGSGIYDGSCNSRLNHAVTVIGYGTSEEDGTKYWIVKNSWGSDWGEEGYMRIARDVGVDGGHCGIAKVASFPTA
>EpiC2B
QLNGYSKKEVTPEDTELLQKAQSNVSAYNSDVTSRICYLKVDSLETQVVSGENYKFHVSGCSVNSDKELGGCANQNCESSKYDIVIYSQSWTNTLKVTSITPAN
```
iptm+ptm_value:
```
    "iptm+ptm": {
        "model_1_multimer_v3_pred_0": 0.26201708916760885,
        "model_2_multimer_v3_pred_0": 0.5724083884093831,
        "model_3_multimer_v3_pred_0": 0.264971085669789,
        "model_4_multimer_v3_pred_0": 0.6864719020996431,
        "model_5_multimer_v3_pred_0": 0.2611876854265976
```

**Comment by cfz1998** [comment]
OHHHH! I made a mistake.

**Comment by cfz1998** [comment]
Another run:
```
    "iptm+ptm": {
        "model_1_multimer_v3_pred_0": 0.7676547179294119,
        "model_2_multimer_v3_pred_0": 0.25740027170461893,
        "model_3_multimer_v3_pred_0": 0.24764345016869405,
        "model_4_multimer_v3_pred_0": 0.8366415275945385,
        "model_5_multimer_v3_pred_0": 0.24840000926394584
    }
```

**Comment by cfz1998** [comment]
Alphafold version:  v2.3.1
GPU: 3090
CUDA Version: 11.6

**Comment by cfz1998** [comment]
[run_alphafold.sh](https://github.com/kalininalab/alphafold_non_docker/blob/main/run_alphafold.sh)

**Comment by FelixHomma** [comment]
> Hi! @HommaF 
> 
> I'm using `alphafold` to structure prediction for "PiP1+EpiC2B". But I get very low `iptm+ptm` value.
> Running code:
> ```
> bash /data/chaofan/software/alphafold-2.3.1/run_alphafold.sh -c reduced_dbs -d /data/chaofan/source/00.alphafold_database/ -o ./dummy_test/ -f t.fa -t 2023-10-17 -m multimer -l 1
> ```
> 
> Input_Fasta:
> ```
> >Pip1
> RNLKELSMLERHENWMVHHGRVYKDDIEKEHRFKTFKENVEFIESFNKNGTQRYKLAINKYADLTTEEFTTSFMGLDTSLLSQQESTATTTSFKYDSVTEVPNSMDWRKRGSVTGVKDQGVCGCCWAFSAAAAIEGAYQIANNELISLSEQQLLDCSTQNKGCEGGLMTVAYDFLLQNNGGGITTETNYPYEEAQNVCKTEQPAAVTINGYEVVPSDESSLLKAVVNQPISVGIAANDEFHMYGSGIYDGSCNSRLNHAVTVIGYGTSEEDGTKYWIVKNSWGSDWGEEGYMRIARDVGVDGGHCGIAKVASFPTA
> >EpiC2B
> QLNGYSKKEVTPEDTELLQKAQSNVSAYNSDVTSRICYLKVDSLETQVVSGENYKFHVSGCSVNSDKELGGCANQNCESSKYDIVIYSQSWTNTLKVTSITPAN
> ```
> iptm+ptm_value:
> ```
>     "iptm+ptm": {
>         "model_1_multimer_v3_pred_0": 0.26201708916760885,
>         "model_2_multimer_v3_pred_0": 0.5724083884093831,
>         "model_3_multimer_v3_pred_0": 0.264971085669789,
>         "model_4_multimer_v3_pred_0": 0.6864719020996431,
>         "model_5_multimer_v3_pred_0": 0.2611876854265976
> ```
> 
> 

Hey @cfz1998,

Based on the Pip1 sequence above, it looks like you included the inhibitory prodomain of Pip1. Could you remodel with only the mature protein sequence? 
Try
```
>Pip1_mature
VTEVPNSMDWRKRGSVTGVKDQGVCGCCWAFSAAAAIEGAYQIANNELISLSEQQLLDCSTQNKGCEGGLMTVAYDFLLQNNGGGITTETNYPYEEAQNVCKTEQPAAVTINGYEVVPSDESSLLKAVVNQPISVGIAANDEFHMYGSGIYDGSCNSRLNHAVTVIGYGTSEEDGTKYWIVKNSWGSDWGEEGYMRIARDVGVDGGHCGIAKVASFPTA
```
I assume that if you inspect the current output PDB files, you will find the prodomain occupying the binding groove. 
Let me know if this helped!

**Comment by cfz1998** [comment]
Wow！
```
    "iptm+ptm": {
        "model_1_multimer_v3_pred_0": 0.9130940645044535,
        "model_2_multimer_v3_pred_0": 0.9080438523780853,
        "model_3_multimer_v3_pred_0": 0.9171108252434494,
        "model_4_multimer_v3_pred_0": 0.9183709633181361,
        "model_5_multimer_v3_pred_0": 0.9209148930632896
```
